server.port=7770
gg.jte.developmentMode=true
gg.jte.usePrecompiledTemplates=false
gg.jte.templateLocation=./src/main/jte
spring.devtools.restart.additional-paths=./src/main/jte
server.servlet.contextPath=
spring.mvc.throw-exception-if-no-handler-found=false
logging.level.gg.jte=trace
logging.level.org.springframework=ERROR
logging.level.org.apache.http=ERROR
server.error.whitelabel.enabled=false
server.error.path=/error
# spring.servlet.multipart.max-file-size=4MB
# spring.servlet.multipart.max-request-size=10MB
spring.main.allow-bean-definition-overriding=true
application-description=@project.description@
application-version=@project.version@
build.timestamp=@maven.build.timestamp@
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always
management.health.elasticsearch.enabled=false
management.health.mail.enabled=false
management.health.ping.enabled=true
spring.main.allow-circular-references=true

spring.mvc.servlet.load-on-startup=1

logging.level.web=TRACE
logging.level.org.springframework.web=TRACE
