<?xml version="1.0"?>
<project
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
        xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>JawaStatsRoot</artifactId>
    <name>root</name>
    <packaging>pom</packaging>
    <groupId>Gryphoon</groupId>
    <version>0.0.1</version>

    <modules>
        <module>wwwroot</module>
    </modules>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <maven.compiler.release>21</maven.compiler.release>
        <version.spring-boot-starter>3.5.9</version.spring-boot-starter>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${version.spring-boot-starter}</version>
                <configuration>
                </configuration>
            </plugin>
        </plugins>
    </build>


</project>
