import java.util.HashMap;
import java.util.Map;

public enum Domain {
    LOCALHOST("localhost", "localhost"),
        I0("i0", "Local network host"),
        A1("a1", "Satellite access host"),
        A2("a2", "Satellite access host"),
        AP("ap", "Asia/Pacific Region"),
        AC("ac", "Ascension Island"),
        AD("ad", "Andorra"),
        AE("ae", "United Arab Emirates"),
        AERO("aero", "Aero/Travel domains"),
        AF("af", "Afghanistan"),
        AG("ag", "Antigua and Barbuda"),
        AI("ai", "Anguilla"),
        AL("al", "Albania"),
        AM("am", "Armenia"),
        AN("an", "Netherlands Antilles"),
        AO("ao", "Angola"),
        AQ("aq", "Antarctica"),
        AR("ar", "Argentina"),
        ARPA("arpa", "Old style Arpanet"),
        AS("as", "American Samoa"),
        AT("at", "Austria"),
        AU("au", "Australia"),
        AW("aw", "Aruba"),
        AX("ax", "Aland islands"),
        AZ("az", "Azerbaijan"),
        BA("ba", "Bosnia-Herzegovina"),
        BB("bb", "Barbados"),
        BD("bd", "Bangladesh"),
        BE("be", "Belgium"),
        BF("bf", "Burkina Faso"),
        BG("bg", "Bulgaria"),
        BH("bh", "Bahrain"),
        BI("bi", "Burundi"),
        BIZ("biz", "Biz domains"),
        BJ("bj", "Benin"),
        BM("bm", "Bermuda"),
        BN("bn", "Brunei Darussalam"),
        BO("bo", "Bolivia"),
        BQ("bq", "Bonaire, Sint Eustatius And Saba"),
        BR("br", "Brazil"),
        BS("bs", "Bahamas"),
        BT("bt", "Bhutan"),
        BV("bv", "Bouvet Island"),
        BW("bw", "Botswana"),
        BY("by", "Belarus"),
        BZ("bz", "Belize"),
        CA("ca", "Canada"),
        CC("cc", "Cocos (Keeling) Islands"),
        CD("cd", "Congo, Democratic Republic of the"),
        CF("cf", "Central African Republic"),
        CG("cg", "Congo"),
        CH("ch", "Switzerland"),
        CI("ci", "Ivory Coast (Cote D'Ivoire)"),
        CK("ck", "Cook Islands"),
        CL("cl", "Chile"),
        CM("cm", "Cameroon"),
        CN("cn", "China"),
        CO("co", "Colombia"),
        COM("com", "Commercial"),
        COOP("coop", "Coop domains"),
        CR("cr", "Costa Rica"),
        CS("cs", "Former Czechoslovakia"),
        CU("cu", "Cuba"),
        CV("cv", "Cape Verde"),
        CW("cw", "Curacao"),
        CX("cx", "Christmas Island"),
        CY("cy", "Cyprus"),
        CZ("cz", "Czech Republic"),
        DE("de", "Germany"),
        DJ("dj", "Djibouti"),
        DK("dk", "Denmark"),
        DM("dm", "Dominica"),
        DO("do", "Dominican Republic"),
        DZ("dz", "Algeria"),
        EC("ec", "Ecuador"),
        EDU("edu", "USA Educational"),
        EE("ee", "Estonia"),
        EG("eg", "Egypt"),
        EH("eh", "Western Sahara"),
        ER("er", "Eritrea"),
        ES("es", "Spain"),
        ET("et", "Ethiopia"),
        EU("eu", "European country"),
        FI("fi", "Finland"),
        FJ("fj", "Fiji"),
        FK("fk", "Falkland Islands"),
        FM("fm", "Micronesia"),
        FO("fo", "Faroe Islands"),
        FR("fr", "France"),
        FX("fx", "France (European Territory)"),
        GA("ga", "Gabon"),
        GB("gb", "Great Britain"),
        GD("gd", "Grenada"),
        GE("ge", "Georgia"),
        GF("gf", "French Guyana"),
        GG("gg", "Guernsey"),
        GH("gh", "Ghana"),
        GI("gi", "Gibraltar"),
        GL("gl", "Greenland"),
        GM("gm", "Gambia"),
        GN("gn", "Guinea"),
        GOV("gov", "USA Government"),
        GP("gp", "Guadeloupe (French)"),
        GQ("gq", "Equatorial Guinea"),
        GR("gr", "Greece"),
        GS("gs", "S. Georgia & S. Sandwich Isls."),
        GT("gt", "Guatemala"),
        GU("gu", "Guam (USA)"),
        GW("gw", "Guinea Bissau"),
        GY("gy", "Guyana"),
        HK("hk", "Hong Kong"),
        HM("hm", "Heard and McDonald Islands"),
        HN("hn", "Honduras"),
        HR("hr", "Croatia"),
        HT("ht", "Haiti"),
        HU("hu", "Hungary"),
        ID("id", "Indonesia"),
        IE("ie", "Ireland"),
        IL("il", "Israel"),
        IM("im", "Isle of Man"),
        IN("in", "India"),
        INFO("info", "Info domains"),
        INT("int", "International"),
        IO("io", "British Indian Ocean Territory"),
        IQ("iq", "Iraq"),
        IR("ir", "Iran"),
        IS("is", "Iceland"),
        IT("it", "Italy"),
        JE("je", "Jersey"),
        JM("jm", "Jamaica"),
        JO("jo", "Jordan"),
        JOBS("jobs", "Jobs domains"),
        JP("jp", "Japan"),
        KE("ke", "Kenya"),
        KG("kg", "Kyrgyzstan"),
        KH("kh", "Cambodia"),
        KI("ki", "Kiribati"),
        KM("km", "Comoros"),
        KN("kn", "Saint Kitts & Nevis Anguilla"),
        KP("kp", "North Korea"),
        KR("kr", "South Korea"),
        KW("kw", "Kuwait"),
        KY("ky", "Cayman Islands"),
        KZ("kz", "Kazakhstan"),
        LA("la", "Laos"),
        LB("lb", "Lebanon"),
        LC("lc", "Saint Lucia"),
        LI("li", "Liechtenstein"),
        LK("lk", "Sri Lanka"),
        LR("lr", "Liberia"),
        LS("ls", "Lesotho"),
        LT("lt", "Lithuania"),
        LU("lu", "Luxembourg"),
        LV("lv", "Latvia"),
        LY("ly", "Libya"),
        MA("ma", "Morocco"),
        MC("mc", "Monaco"),
        MD("md", "Moldova"),
        ME("me", "Montenegro"),
        MF("mf", "Saint-Martin (French)"),
        MG("mg", "Madagascar"),
        MH("mh", "Marshall Islands"),
        MIL("mil", "USA Military"),
        MK("mk", "Macedonia"),
        ML("ml", "Mali"),
        MM("mm", "Myanmar"),
        MN("mn", "Mongolia"),
        MO("mo", "Macau"),
        MOBI("mobi", "Mobi domains"),
        MP("mp", "Northern Mariana Islands"),
        MQ("mq", "Martinique (French)"),
        MR("mr", "Mauritania"),
        MS("ms", "Montserrat"),
        MT("mt", "Malta"),
        MU("mu", "Mauritius"),
        MUSEUM("museum", "Museum domains"),
        MV("mv", "Maldives"),
        MW("mw", "Malawi"),
        MX("mx", "Mexico"),
        MY("my", "Malaysia"),
        MZ("mz", "Mozambique"),
        NA("na", "Namibia"),
        NAME("name", "Name domains"),
        NATO("nato", "NATO"),
        NC("nc", "New Caledonia (French)"),
        NE("ne", "Niger"),
        NET("net", "Network"),
        NF("nf", "Norfolk Island"),
        NG("ng", "Nigeria"),
        NI("ni", "Nicaragua"),
        NL("nl", "Netherlands"),
        NO("no", "Norway"),
        NP("np", "Nepal"),
        NR("nr", "Nauru"),
        NT("nt", "Neutral Zone"),
        NU("nu", "Niue"),
        NZ("nz", "New Zealand"),
        OM("om", "Oman"),
        ORG("org", "Non-Profit Organizations"),
        PA("pa", "Panama"),
        PE("pe", "Peru"),
        PF("pf", "Polynesia (French)"),
        PG("pg", "Papua New Guinea"),
        PH("ph", "Philippines"),
        PK("pk", "Pakistan"),
        PL("pl", "Poland"),
        PM("pm", "Saint Pierre and Miquelon"),
        PN("pn", "Pitcairn Island"),
        PR("pr", "Puerto Rico"),
        PRO("pro", "Professional domains"),
        PS("ps", "Palestinian Territories"),
        PT("pt", "Portugal"),
        PW("pw", "Palau"),
        PY("py", "Paraguay"),
        QA("qa", "Qatar"),
        RE("re", "Reunion (French)"),
        RO("ro", "Romania"),
        RS("rs", "Republic of Serbia"),
        RU("ru", "Russian Federation"),
        RW("rw", "Rwanda"),
        SA("sa", "Saudi Arabia"),
        SB("sb", "Solomon Islands"),
        SC("sc", "Seychelles"),
        SD("sd", "Sudan"),
        SE("se", "Sweden"),
        SG("sg", "Singapore"),
        SH("sh", "Saint Helena"),
        SI("si", "Slovenia"),
        SJ("sj", "Svalbard and Jan Mayen Islands"),
        SK("sk", "Slovak Republic"),
        SL("sl", "Sierra Leone"),
        SM("sm", "San Marino"),
        SN("sn", "Senegal"),
        SO("so", "Somalia"),
        SR("sr", "Suriname"),
        ST("st", "Sao Tome and Principe"),
        SU("su", "Former USSR"),
        SV("sv", "El Salvador"),
        SX("sx", "Sint Maarten"),
        SY("sy", "Syria"),
        SZ("sz", "Swaziland"),
        TC("tc", "Turks and Caicos Islands"),
        TD("td", "Chad"),
        TF("tf", "French Southern Territories"),
        TG("tg", "Togo"),
        TH("th", "Thailand"),
        TJ("tj", "Tadjikistan"),
        TK("tk", "Tokelau"),
        TM("tm", "Turkmenistan"),
        TN("tn", "Tunisia"),
        TO("to", "Tonga"),
        TP("tp", "East Timor"),
        TR("tr", "Turkey"),
        TT("tt", "Trinidad and Tobago"),
        TV("tv", "Tuvalu"),
        TW("tw", "Taiwan"),
        TZ("tz", "Tanzania"),
        UA("ua", "Ukraine"),
        UG("ug", "Uganda"),
        UK("uk", "United Kingdom"),
        UM("um", "USA Minor Outlying Islands"),
        US("us", "United States"),
        UY("uy", "Uruguay"),
        UZ("uz", "Uzbekistan"),
        VA("va", "Vatican City State"),
        VC("vc", "Saint Vincent & Grenadines"),
        VE("ve", "Venezuela"),
        VG("vg", "Virgin Islands (British)"),
        VI("vi", "Virgin Islands (USA)"),
        VN("vn", "Vietnam"),
        VU("vu", "Vanuatu"),
        WF("wf", "Wallis and Futuna Islands"),
        WS("ws", "Samoa Islands"),
        YE("ye", "Yemen"),
        YT("yt", "Mayotte"),
        YU("yu", "Yugoslavia"),
        ZA("za", "South Africa"),
        ZM("zm", "Zambia"),
        ZR("zr", "Zaire"),
        ZW("zw", "Zimbabwe");

    private final String tld;
    private final String description;
    private static final Map<String, Domain> BY_TLD = new HashMap<>();

    static {
        for (Domain domain : values()) {
            BY_TLD.put(domain.tld, domain);
        }
    }

        Domain(String tld, String description) {
        this.tld = tld;
        this.description = description;
    }

    public String getTld() { return tld; }
    public String getDescription() { return description; }

    public static Domain fromTld(String tld) {
        return BY_TLD.get(tld.toLowerCase());
    }
}
